# _config.yml
title: VAIRA Advisory
url: "https://raphaelheeb.github.io"
baseurl: "/vaira-advisory"    # IMPORTANT for project sites
theme: null                   # Youâ€™re using custom CSS, not a Jekyll theme
